apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuberoapp.fullname" . }}-web
  labels:
    {{- include "kuberoapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  {{- if and (.Values.autoscaling.enabled) (lt (.Values.web.autoscaling.minReplicas | float64) 1.0) }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "kuberoapp.selectorLabels" . | nindent 6 }}-web
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if and ( .Values.sleep ) (ne .Values.sleep "disabled") }}
        zeropod.ctrox.dev/scaledown-duration: {{ .Values.sleep }}
        {{- end }}
      labels:
        {{- include "kuberoapp.selectorLabels" . | nindent 8 }}-web
    spec:
      {{- if and ( .Values.sleep ) (ne .Values.sleep "disabled") }}
      runtimeClassName: zeropod
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else if eq .Values.deploymentstrategy "git" }}
      imagePullSecrets:
        - name: kubero-pull-secret # created by kuberopipeline/phases.yaml
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kuberoapp.serviceAccountName" . }}  
      {{- if and (eq .Values.deploymentstrategy "git") (eq .Values.buildstrategy "plain") }}
      initContainers:
        - name: {{ .Chart.Name }}-fetcher
          securityContext:
            {{- toYaml .Values.image.fetch.securityContext | nindent 12 }}
          image: "{{ .Values.image.fetch.repository }}:{{ .Values.image.fetch.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
            - name: GIT_REPOSITORY
              value: {{ include "kuberoapp.clone_url" . | quote }}
            {{- if .Values.branch }}
            - name: GIT_BRANCH
              value: {{ .Values.branch | quote }}
            {{- end }}
            {{- if .Values.ref }}
            - name: GIT_REF
              value: {{ .Values.ref | quote }}
            {{- end }}
            {{- if .Values.image.build.command }}
            - name: KUBERO_BUILDPACK_DEFAULT_BUILD_CMD
              value: {{ .Values.image.build.command | quote }}
            {{- end }}
            {{- if .Values.image.run.command }}
            - name: KUBERO_BUILDPACK_DEFAULT_RUN_CMD
              value: {{ .Values.image.run.command | quote }}
            {{- end }}
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /home/kubero/.ssh-mounted
              name: deployment-keys
              readOnly: true
            - mountPath: /app
              name: app-storage
        - name: {{ .Chart.Name }}-builder
          securityContext:
            {{- toYaml .Values.image.build.securityContext | nindent 12 }}
          image: "{{ .Values.image.build.repository }}:{{ .Values.image.build.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["./init-build.sh"]
          volumeMounts:
            - mountPath: /app
              name: app-storage
            {{- range .Values.extraVolumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.image.run.securityContext | nindent 12 }}
          {{- if or (eq .Values.deploymentstrategy "docker") (or (eq .Values.buildstrategy "dockerfile") (eq .Values.buildstrategy "nixpacks") (eq .Values.buildstrategy "buildpacks") (eq .Values.buildstrategy "external")) }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          {{- if .Values.image.command }}
          command:
            {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- else }}
          image: "{{ .Values.image.run.repository }}:{{ .Values.image.run.tag | default "latest" }}"
          workingDir: /app
          command: ["./init-web.sh"]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROC_TYPE
              value: web
            - name: PORT
              value: {{ .Values.image.containerPort | default "8080" | quote }}
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort | default "8080" }}
              protocol: TCP
          {{- if or ( not .Values.sleep ) (eq .Values.sleep "disabled") }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
            failureThreshold: 30
          {{- end }}
          volumeMounts:
            {{- if and (eq .Values.deploymentstrategy "git") (eq .Values.buildstrategy "plain") }}
            - mountPath: /app
              name: app-storage
              {{- if or .Values.image.run.readOnlyAppStorage (not (hasKey .Values.image.run "readOnlyAppStorage")) }}
              readOnly: true
              {{- end }}
            {{- end }}
            - mountPath: /tmp
              name: tmp-storage
              readOnly: false
            {{- range .Values.extraVolumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: deployment-keys
        secret:
          secretName: deployment-keys
      - name: app-storage
        emptyDir: {}
      - name: tmp-storage
        emptyDir: {}
      {{- range .Values.extraVolumes }}
      - name: {{ .name }}
        {{- if .emptyDir }}
        emptyDir: {}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
